name: shopify_storefront
description: Storefront API gives you full creative control to add Shopify buying experiences anywhere your customers are, including websites, apps, and video games.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.14.2 <3.0.0"

dependencies:
  graphql: ^5.0.0
  shopify_storefront_core:
    path: ../shopify_storefront_core

dev_dependencies:
  test: ^1.17.12
  derry: ^1.4.3

scripts: ../../derry.yaml
