name: shopify_plus
description: A new package which provides help in creating a mobile app of a shopify store.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  graphql: ^5.0.0-nullsafety.4
  freezed_annotation: ^0.14.3
  json_serializable: ^5.0.2
  shared_preferences: ^2.0.8
  intl: ^0.17.0
  url_launcher: ^6.0.12
  requests:
    git:
      url: https://github.com/mrgnhnt96/shopify_plus.git
      path: packages/shopify_requests

dev_dependencies:
  build_runner: ^2.1.2
  freezed: ^0.14.5
  injectable_generator: ^1.5.2
  pedantic: ^1.11.1
  derry: ^1.4.3

scripts: ../../derry.yaml
