name: shopify_core
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  json_serializable: ^5.0.2
  freezed_annotation: ^0.14.3

dev_dependencies:
  test: ^1.17.12
  build_runner: ^2.1.2
  freezed: ^0.14.5
  derry: ^1.4.3

scripts: ../../derry.yaml
